### ISSUE TITLE
Simulator incompatible with last CORE

### ISSUE THREAD

**Issue by calabr** [grblHAL/Simulator#3]
After last updates simulator code become incompatible with current grblHAL core, available by reference.
try to build it end with errors

driver.c: In function ‘driver_init’:
driver.c:446:20: error: ‘driver_cap_t’ has no member named ‘spindle_dir’; did you mean ‘spindle_pid’?
  446 |     hal.driver_cap.spindle_dir = On;
         |                    ^~~~~~~~~~~
         |  spindle_pid
driver.c:448:19: error: ‘driver_cap_t’ has no member named ‘variable_spindle’
  448 |     hal.driver_cap.variable_spindle = On;
         |                    ^

**Comment by terjeio** [comment]
[This PR](https://github.com/grblHAL/Simulator/pull/2) has the changes required.
